//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blazor.UI.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blazor.UI.Shared.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 600 series.
        /// </summary>
        public static string _600_series {
            get {
                return ResourceManager.GetString("600_series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Area.
        /// </summary>
        public static string access_area {
            get {
                return ResourceManager.GetString("access_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessory {0} completed.
        /// </summary>
        public static string accessory_completed {
            get {
                return ResourceManager.GetString("accessory_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been changed.
        /// </summary>
        public static string account_has_been_changed {
            get {
                return ResourceManager.GetString("account_has_been_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↓↓↓↓↓↓ Add ↓↓↓↓↓↓.
        /// </summary>
        public static string add_arrow {
            get {
                return ResourceManager.GetString("add_arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add PO.
        /// </summary>
        public static string add_po {
            get {
                return ResourceManager.GetString("add_po", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↓↓↓↓↓↓ Add to container ↓↓↓↓↓↓.
        /// </summary>
        public static string add_to_container {
            get {
                return ResourceManager.GetString("add_to_container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to pallet.
        /// </summary>
        public static string add_to_pallet {
            get {
                return ResourceManager.GetString("add_to_pallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↓↓↓↓↓↓ Add to production schedule ↓↓↓↓↓↓.
        /// </summary>
        public static string add_to_production_schedule {
            get {
                return ResourceManager.GetString("add_to_production_schedule", resourceCulture);
            }
        }
    }
}
